### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by Mperv** [tomlokhorst/swift-cancellationtoken#1]
When CancellationToken object is created it obtains strong reference to CancellationTokenSource object via state = .Pending(source)
But CancellationTokenSource object have strong reference to CancellationToken object via token field. So, neither CancellationTokenSource object, nor CancellationToken will ever be released.

**Comment by tomlokhorst** [comment]
Yes, good point.

I'm looking into how to fix this, preferably without giving up performance.

**Comment by Mperv** [comment]
Well, I'm pretty sure, that creation of CancellationToken object on demand will not hurt performance in a noticeable manner. It is struct, it will copy on each assignment anyway. So, no need for a reference from CancellationTokenSource.

**Comment by tomlokhorst** [comment]
Right, of course.

I've changed the `token` to be a computed property: d2e2e69a790f9a27f02b3449ba7f66e15c49d22c

If you're using cocoa pods, this has been released as version 0.1.1
